document.writeln("<div class=\"container-fluid\" id=\"div8\">");
document.writeln("			<div class=\"row\">");
document.writeln("				<div class=\"col-lg-4 col-xs-4\">");
document.writeln("					<ul>");
document.writeln("						<li><a href=\"\">产品展示</a></li>");
document.writeln("						<li><a href=\"\">连衣裙</a></li>");
document.writeln("						<li><a href=\"\">牛仔裤</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\"col-lg-4 col-xs-4\">");
document.writeln("					<ul>");
document.writeln("						<li><a href=\"\">服务专区</a></li>");
document.writeln("						<li><a href=\"\">售后服务</a></li>");
document.writeln("						<li><a href=\"\">经销商加盟</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\"col-lg-4 col-xs-4\">");
document.writeln("					<ul>");
document.writeln("						<li><a href=\"\">关于我们</a></li>");
document.writeln("						<li><a href=\"\">版权所有：轻衣坊有限责任公司</a></li>");
document.writeln("						<li><a href=\"\">地址：广州市海珠区仑头路100号</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");