document.writeln("");
document.writeln("<body>");
document.writeln("	<nav class=\"navbar navbar-fixed-top\" id=\"div1\">");
document.writeln("	  <div class=\"container\">");
document.writeln("	    <div class=\"navbar-header\">");
document.writeln("	      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">");
document.writeln("	        <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("	        <span class=\"icon-bar\"></span>");
document.writeln("	        <span class=\"icon-bar\"></span>");
document.writeln("	        <span class=\"icon-bar\"></span>");
document.writeln("	      </button>");
document.writeln("			<img src=\"imgs/logo.jpg\"  class=\"text-center\">");
document.writeln("		</div>");
document.writeln("	");
document.writeln("	    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.writeln("	      <ul class=\"nav navbar-nav\">");
document.writeln("	        <li class=\"active\"><a href=\"index.html\">首页 <span class=\"sr-only\">(current)</span></a></li>");
document.writeln("	        <li class=\"dropdown\">");
document.writeln("	          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">春夏新品 <span class=\"caret\"></span></a>");
document.writeln("	          <ul class=\"dropdown-menu\">");
document.writeln("	            <li><a href=\"lianyiqun.html\">新品连衣裙</a></li>");
document.writeln("	            <li><a href=\"waitao.html\">新品外套</a></li>");
document.writeln("	            <li><a href=\"weiyi.html\">新品卫衣</a></li>");
document.writeln("	            <li><a href=\"niuzaiku.html\">新品牛仔裤</a></li>");
document.writeln("	            <li><a href=\"zhenzhishan.html\">新品针织衫</a></li>");
document.writeln("	            <li><a href=\"xiuxianku.html\">新品休闲裤</a></li>");
document.writeln("	          </ul>");
document.writeln("	        </li>");
document.writeln("			");
document.writeln("	        <li class=\"dropdown\">");
document.writeln("	          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">商品分类 <span class=\"caret\"></span></a>");
document.writeln("	          <ul class=\"dropdown-menu\">");
document.writeln("	           <li><a href=\"lianyiqun.html\">连衣裙</a></li>");
document.writeln("	           <li><a href=\"waitao.html\">外套</a></li>");
document.writeln("	           <li><a href=\"weiyi.html\">卫衣</a></li>");
document.writeln("	           <li><a href=\"niuzaiku.html\">牛仔裤</a></li>");
document.writeln("	           <li><a href=\"zhenzhishan.html\">针织衫</a></li>");
document.writeln("	           <li><a href=\"xiuxianku.html\">休闲裤</a></li>");
document.writeln("	          </ul>");
document.writeln("	        </li>");
document.writeln("			<li><a href=\"lianyiqun.html\">连衣裙</a></li>");
document.writeln("			<li><a href=\"niuzaiku.html\">牛仔裤</a></li>");
document.writeln("	      </ul>");
document.writeln("	      <form class=\"navbar-form navbar-left\" role=\"search\">");
document.writeln("	       <div class=\"input-group\">");
document.writeln("	       	<input type=\"text\" class=\"form-control \" placeholder=\"连衣裙\">");
document.writeln("	       	<span class=\"input-group-btn\"><button type=\"button\" class=\"btn btn-warning\">  <span class=\"glyphicon glyphicon-search \"></span> 搜索</button></span>");
document.writeln("	       </div>");
document.writeln("	      </form>");
document.writeln("	      <ul class=\"nav navbar-nav navbar-right\">");
document.writeln("	        <li><a href=\"denglu.html\">登录</a></li>");
document.writeln("	        <li><a href=\"zhuce.html\">注册</a></li>");
document.writeln("	      </ul>");
document.writeln("	    </div>");
document.writeln("	  </div>");
document.writeln("	</nav>");
document.writeln("");